package Compilador;

// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: src/Lexer.flex

import compilerTools.Token;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
class Lexer {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\5\22\0\1\6"+
    "\1\7\1\10\1\0\1\11\1\12\2\0\1\13\1\14"+
    "\1\15\1\12\1\0\1\12\1\16\1\17\12\20\2\0"+
    "\1\21\1\22\1\21\2\0\5\23\1\24\7\23\1\25"+
    "\5\23\1\26\6\23\1\0\1\27\4\0\1\30\1\31"+
    "\1\32\1\33\1\34\1\35\1\36\1\37\1\40\1\36"+
    "\1\41\1\42\1\43\1\44\1\45\1\46\1\36\1\47"+
    "\1\50\1\51\1\52\1\36\1\53\1\54\1\55\1\36"+
    "\1\56\1\0\1\57\7\0\1\3\u01a2\0\2\3\326\0"+
    "\u0100\60";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\2\2\1\1\1\2\1\3\1\4\1\5"+
    "\1\3\1\6\21\1\1\7\1\10\17\1\1\6\20\0"+
    "\1\11\1\0\1\11\27\0\1\11\1\0\1\11\2\0"+
    "\1\6\23\0\1\12\25\0\1\12\7\0\1\2\11\0"+
    "\2\13\20\0\2\14\1\15\11\0\1\16\2\17\3\0"+
    "\1\20\2\21\1\22";

  private static int [] zzUnpackAction() {
    int [] result = new int[194];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\61\0\142\0\142\0\223\0\304\0\365\0\142"+
    "\0\142\0\142\0\u0126\0\304\0\u0157\0\u0188\0\u01b9\0\u01ea"+
    "\0\u021b\0\u024c\0\u027d\0\u02ae\0\u02df\0\u0310\0\u0341\0\u0372"+
    "\0\u03a3\0\u03d4\0\u0405\0\u0436\0\u0467\0\142\0\142\0\u0498"+
    "\0\u04c9\0\u04fa\0\u052b\0\u055c\0\u058d\0\u05be\0\u05ef\0\u0620"+
    "\0\u0651\0\u0682\0\u06b3\0\u06e4\0\u0715\0\u0746\0\142\0\u0777"+
    "\0\u07a8\0\u07d9\0\u080a\0\u083b\0\u086c\0\u089d\0\u08ce\0\u03a3"+
    "\0\u08ff\0\u0930\0\u0961\0\u0992\0\u09c3\0\u09f4\0\u0a25\0\142"+
    "\0\u0a56\0\u0a87\0\u0ab8\0\u0ae9\0\u0b1a\0\u0b4b\0\u0b7c\0\u0bad"+
    "\0\u0bde\0\u0c0f\0\u0c40\0\u0c71\0\u052b\0\u0ca2\0\u0cd3\0\u0d04"+
    "\0\u0d35\0\u0682\0\u0d66\0\u0d97\0\u0dc8\0\u0df9\0\u0e2a\0\u0e5b"+
    "\0\u0e8c\0\u052b\0\u0ebd\0\u0eee\0\u0f1f\0\u0f50\0\u052b\0\u0f81"+
    "\0\u0fb2\0\u0fe3\0\u1014\0\u1045\0\u1076\0\u10a7\0\u10d8\0\u1109"+
    "\0\u113a\0\u116b\0\u119c\0\u11cd\0\u11fe\0\u122f\0\u1260\0\u1291"+
    "\0\u12c2\0\u12f3\0\142\0\u1324\0\u1355\0\u1386\0\u13b7\0\u13e8"+
    "\0\u1419\0\u144a\0\u147b\0\u14ac\0\u14dd\0\u150e\0\u153f\0\u1570"+
    "\0\u15a1\0\u15d2\0\u1603\0\u1634\0\u1665\0\u1696\0\u16c7\0\u16f8"+
    "\0\u052b\0\u1729\0\u175a\0\u178b\0\u17bc\0\u17ed\0\u181e\0\u184f"+
    "\0\u10a7\0\u1880\0\u18b1\0\u18e2\0\u0a87\0\u1913\0\u1944\0\u1975"+
    "\0\u19a6\0\u19d7\0\142\0\u1a08\0\u1a39\0\u1a6a\0\u1a9b\0\u1acc"+
    "\0\u1afd\0\u1b2e\0\u0eee\0\u1b5f\0\u1b90\0\u1bc1\0\u1bf2\0\u1c23"+
    "\0\u1c54\0\u1c85\0\u1cb6\0\u1ce7\0\142\0\u1d18\0\142\0\u1d49"+
    "\0\u1d7a\0\u1dab\0\u1ddc\0\u1e0d\0\u1e3e\0\u1e6f\0\u1ea0\0\u1ed1"+
    "\0\142\0\142\0\u1f02\0\u1f33\0\u1f64\0\u1f95\0\142\0\142"+
    "\0\u1fc6\0\142";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[194];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\2\4\1\0\1\4\1\5\1\4\1\6\1\3"+
    "\1\7\1\10\1\11\1\12\1\10\1\3\1\13\1\3"+
    "\1\14\1\6\1\3\1\15\1\16\1\17\1\3\1\20"+
    "\1\21\1\22\1\3\1\23\1\24\2\3\1\25\1\3"+
    "\1\26\1\3\1\27\1\30\1\31\1\32\1\33\1\34"+
    "\1\3\1\35\2\3\1\36\1\37\1\0\1\3\2\4"+
    "\1\0\1\4\1\5\1\4\1\6\1\3\1\7\1\10"+
    "\1\11\1\12\1\10\1\3\1\13\1\3\1\14\1\6"+
    "\1\3\1\15\1\16\1\17\1\3\1\40\1\41\1\42"+
    "\1\43\1\44\1\45\2\43\1\46\1\43\1\47\1\43"+
    "\1\50\1\51\1\52\1\53\1\54\1\55\1\43\1\56"+
    "\2\43\1\36\1\37\64\0\1\4\100\0\1\57\36\0"+
    "\2\7\1\4\2\7\1\5\53\7\15\0\1\60\1\0"+
    "\1\10\71\0\1\61\75\0\1\62\62\0\1\63\55\0"+
    "\1\64\61\0\1\65\1\0\1\66\50\0\1\67\2\0"+
    "\1\70\2\0\1\71\55\0\1\72\11\0\1\73\46\0"+
    "\1\74\2\0\1\75\1\0\1\76\2\0\1\77\43\0"+
    "\1\100\5\0\1\101\1\102\3\0\1\100\40\0\1\103"+
    "\75\0\1\104\62\0\1\57\41\0\1\105\64\0\1\106"+
    "\75\0\1\107\56\0\1\110\50\0\1\111\7\0\1\112"+
    "\17\0\1\113\13\0\1\114\4\0\1\113\14\115\1\116"+
    "\11\115\11\0\1\113\13\0\1\114\4\0\1\113\15\115"+
    "\1\117\1\115\1\120\6\115\11\0\1\113\13\0\1\114"+
    "\4\0\1\113\7\115\1\121\2\115\1\122\2\115\1\123"+
    "\10\115\11\0\1\113\13\0\1\114\4\0\1\113\26\115"+
    "\11\0\1\113\13\0\1\114\4\0\1\113\12\115\1\124"+
    "\11\115\1\125\1\115\11\0\1\113\13\0\1\114\4\0"+
    "\1\113\12\115\1\126\2\115\1\127\1\115\1\130\2\115"+
    "\1\131\3\115\11\0\1\113\13\0\1\114\4\0\1\113"+
    "\5\115\1\132\5\115\1\133\1\134\3\115\1\132\5\115"+
    "\11\0\1\113\13\0\1\114\4\0\1\113\1\135\25\115"+
    "\11\0\1\113\13\0\1\114\4\0\1\113\15\115\1\136"+
    "\10\115\11\0\1\113\13\0\1\114\4\0\1\113\17\115"+
    "\1\137\6\115\11\0\1\113\13\0\1\114\4\0\1\113"+
    "\1\140\25\115\11\0\1\113\13\0\1\114\4\0\1\113"+
    "\4\115\1\141\21\115\11\0\1\113\13\0\1\114\4\0"+
    "\1\113\21\115\1\142\4\115\11\0\1\113\13\0\1\114"+
    "\4\0\1\113\17\115\1\143\6\115\11\0\1\113\13\0"+
    "\1\114\4\0\1\113\7\115\1\144\7\115\1\145\6\115"+
    "\3\0\15\146\1\147\43\146\42\0\1\150\62\0\1\151"+
    "\66\0\1\151\41\0\1\57\72\0\1\152\47\0\1\153"+
    "\54\0\1\107\74\0\1\154\54\0\1\155\7\0\1\151"+
    "\42\0\1\156\73\0\1\157\62\0\1\100\56\0\1\160"+
    "\57\0\1\161\62\0\1\162\63\0\1\163\52\0\1\164"+
    "\66\0\1\57\57\0\1\165\40\0\1\166\20\0\1\167"+
    "\56\0\1\163\66\0\1\100\43\0\1\170\60\0\1\171"+
    "\42\0\1\114\44\0\1\172\1\0\1\173\7\0\1\174"+
    "\3\0\1\175\1\0\1\176\1\172\37\0\1\113\13\0"+
    "\1\114\4\0\1\113\3\115\1\137\22\115\11\0\1\113"+
    "\13\0\1\114\4\0\1\113\15\115\1\177\10\115\11\0"+
    "\1\113\13\0\1\114\4\0\1\113\4\115\1\200\21\115"+
    "\11\0\1\113\13\0\1\114\4\0\1\113\1\142\25\115"+
    "\11\0\1\113\13\0\1\114\4\0\1\113\14\115\1\201"+
    "\11\115\11\0\1\113\13\0\1\114\4\0\1\113\10\115"+
    "\1\202\7\115\1\203\5\115\11\0\1\113\13\0\1\114"+
    "\4\0\1\113\2\115\1\204\23\115\11\0\1\113\13\0"+
    "\1\114\4\0\1\113\15\115\1\205\10\115\11\0\1\113"+
    "\13\0\1\114\4\0\1\113\17\115\1\132\6\115\11\0"+
    "\1\113\13\0\1\114\4\0\1\113\15\115\1\206\10\115"+
    "\11\0\1\113\13\0\1\114\4\0\1\113\14\115\1\207"+
    "\11\115\11\0\1\113\13\0\1\114\4\0\1\113\16\115"+
    "\1\210\7\115\11\0\1\113\13\0\1\114\4\0\1\113"+
    "\21\115\1\211\4\115\11\0\1\113\13\0\1\114\4\0"+
    "\1\113\13\115\1\212\12\115\11\0\1\113\13\0\1\114"+
    "\4\0\1\113\21\115\1\137\4\115\11\0\1\113\13\0"+
    "\1\114\4\0\1\113\20\115\1\213\5\115\11\0\1\113"+
    "\13\0\1\114\4\0\1\113\1\214\20\115\1\215\4\115"+
    "\11\0\1\113\13\0\1\114\4\0\1\113\17\115\1\211"+
    "\6\115\11\0\1\113\13\0\1\114\4\0\1\113\25\115"+
    "\1\132\11\0\1\113\13\0\1\114\4\0\1\113\10\115"+
    "\1\216\15\115\11\0\1\113\13\0\1\114\4\0\1\113"+
    "\10\115\1\217\15\115\3\0\15\146\1\220\60\146\1\220"+
    "\1\146\1\221\41\146\50\0\1\151\44\0\1\100\66\0"+
    "\1\163\46\0\1\222\101\0\1\223\44\0\1\100\57\0"+
    "\1\224\54\0\1\225\73\0\1\100\47\0\1\226\73\0"+
    "\1\227\44\0\1\230\77\0\1\100\43\0\1\100\77\0"+
    "\1\231\50\0\1\151\67\0\1\151\17\0\1\173\7\0"+
    "\1\174\3\0\1\175\1\0\1\176\40\0\1\173\1\0"+
    "\1\232\7\0\1\173\2\0\33\173\5\0\3\233\1\234"+
    "\10\0\1\235\1\0\1\174\70\0\1\236\77\0\1\237"+
    "\17\0\1\113\13\0\1\114\4\0\1\113\12\115\1\211"+
    "\13\115\11\0\1\113\13\0\1\114\4\0\1\113\1\240"+
    "\25\115\11\0\1\113\13\0\1\114\4\0\1\113\21\115"+
    "\1\241\4\115\11\0\1\113\13\0\1\114\4\0\1\113"+
    "\5\115\1\132\20\115\11\0\1\113\13\0\1\114\4\0"+
    "\1\113\4\115\1\132\21\115\11\0\1\113\13\0\1\114"+
    "\4\0\1\113\4\115\1\242\21\115\11\0\1\113\13\0"+
    "\1\114\4\0\1\113\1\243\25\115\11\0\1\113\13\0"+
    "\1\114\4\0\1\113\13\115\1\132\12\115\11\0\1\113"+
    "\13\0\1\114\4\0\1\113\2\115\1\244\23\115\11\0"+
    "\1\113\13\0\1\114\4\0\1\113\15\115\1\245\10\115"+
    "\11\0\1\113\13\0\1\114\4\0\1\113\1\115\1\246"+
    "\24\115\11\0\1\113\13\0\1\114\4\0\1\113\20\115"+
    "\1\132\5\115\11\0\1\113\13\0\1\114\4\0\1\113"+
    "\3\115\1\132\22\115\11\0\1\113\13\0\1\114\4\0"+
    "\1\113\22\115\1\247\3\115\11\0\1\113\13\0\1\114"+
    "\4\0\1\113\12\115\1\203\13\115\11\0\1\113\13\0"+
    "\1\114\4\0\1\113\21\115\1\203\4\115\3\0\15\146"+
    "\1\220\1\146\1\4\41\146\41\0\1\100\57\0\1\250"+
    "\66\0\1\251\63\0\1\252\56\0\1\251\44\0\1\253"+
    "\74\0\1\254\13\0\3\255\1\256\55\0\1\257\76\0"+
    "\1\260\102\0\1\261\70\0\1\262\14\0\1\113\13\0"+
    "\1\114\4\0\1\113\11\115\1\132\14\115\11\0\1\113"+
    "\13\0\1\114\4\0\1\113\10\115\1\263\15\115\11\0"+
    "\1\113\13\0\1\114\4\0\1\113\16\115\1\264\7\115"+
    "\11\0\1\113\13\0\1\114\4\0\1\113\21\115\1\265"+
    "\4\115\11\0\1\113\13\0\1\114\4\0\1\113\17\115"+
    "\1\264\6\115\11\0\1\113\13\0\1\114\4\0\1\113"+
    "\3\115\1\266\22\115\11\0\1\113\13\0\1\114\4\0"+
    "\1\113\17\115\1\267\6\115\47\0\1\63\65\0\1\100"+
    "\47\0\1\270\50\0\1\100\74\0\1\100\16\0\1\271"+
    "\60\0\3\272\1\273\12\0\1\260\110\0\1\262\44\0"+
    "\1\274\32\0\1\113\13\0\1\114\4\0\1\113\14\115"+
    "\1\275\11\115\11\0\1\113\13\0\1\114\4\0\1\113"+
    "\21\115\1\132\4\115\11\0\1\113\13\0\1\114\4\0"+
    "\1\113\10\115\1\276\15\115\11\0\1\113\13\0\1\114"+
    "\4\0\1\113\1\132\25\115\11\0\1\113\13\0\1\114"+
    "\4\0\1\113\14\115\1\132\11\115\50\0\1\254\15\0"+
    "\1\277\60\0\3\300\1\301\61\0\1\113\13\0\1\114"+
    "\4\0\1\113\22\115\1\203\3\115\11\0\1\113\13\0"+
    "\1\114\4\0\1\113\15\115\1\267\10\115\5\0\1\302"+
    "\56\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[8183];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\2\11\3\1\3\11\23\1\2\11\17\1\1\11"+
    "\20\0\1\11\1\0\1\1\27\0\1\1\1\0\1\1"+
    "\2\0\1\1\23\0\1\11\25\0\1\1\7\0\1\1"+
    "\11\0\1\11\1\1\20\0\1\11\1\1\1\11\11\0"+
    "\2\11\1\1\3\0\2\11\1\1\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[194];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    private Token token(String lexeme, String lexicalComp, int line, int column){
        return new Token(lexeme, lexicalComp, line+1, column+1);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      if (zzMarkedPosL > zzStartRead) {
        switch (zzBufferL[zzMarkedPosL-1]) {
        case '\n':
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':  // fall through
          zzAtBOL = true;
          break;
        case '\r': 
          if (zzMarkedPosL < zzEndReadL)
            zzAtBOL = zzBufferL[zzMarkedPosL] != '\n';
          else if (zzAtEOF)
            zzAtBOL = false;
          else {
            boolean eof = zzRefill();
            zzMarkedPosL = zzMarkedPos;
            zzEndReadL = zzEndRead;
            zzBufferL = zzBuffer;
            if (eof) 
              zzAtBOL = false;
            else 
              zzAtBOL = zzBufferL[zzMarkedPosL] != '\n';
          }
          break;
        default:
          zzAtBOL = false;
        }
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      if (zzAtBOL)
        zzState = ZZ_LEXSTATE[zzLexicalState+1];
      else
        zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return token(yytext(), "ERROR", yyline, yycolumn);
            }
            // fall through
          case 19: break;
          case 2:
            { /*Ignorar*/
            }
            // fall through
          case 20: break;
          case 3:
            { return token(yytext(), "OPERADOR MATEMATICO", yyline, yycolumn);
            }
            // fall through
          case 21: break;
          case 4:
            { return token(yytext(), "PARENTESIS ABIERTO", yyline, yycolumn);
            }
            // fall through
          case 22: break;
          case 5:
            { return token(yytext(), "PARENTESIS CERRADO", yyline, yycolumn);
            }
            // fall through
          case 23: break;
          case 6:
            { return token(yytext(), "OPERADOR LOGICO", yyline, yycolumn);
            }
            // fall through
          case 24: break;
          case 7:
            { return token(yytext(), "LLAVE ABIERTA", yyline, yycolumn);
            }
            // fall through
          case 25: break;
          case 8:
            { return token(yytext(), "LLAVE CERRADA", yyline, yycolumn);
            }
            // fall through
          case 26: break;
          case 9:
            { return token(yytext(), "PALABRA RESERVADA", yyline, yycolumn);
            }
            // fall through
          case 27: break;
          case 10:
            { return token(yytext(), "TIPO DE DATO", yyline, yycolumn);
            }
            // fall through
          case 28: break;
          case 11:
            // lookahead expression with fixed lookahead length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, zzEndRead - zzStartRead, zzMarkedPos, -1);
            { return token(yytext(), "VARIABLE ENTERA", yyline, yycolumn);
            }
            // fall through
          case 29: break;
          case 12:
            // lookahead expression with fixed lookahead length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, zzEndRead - zzStartRead, zzMarkedPos, -1);
            { return token(yytext(), "VARIABLE STR", yyline, yycolumn);
            }
            // fall through
          case 30: break;
          case 13:
            // lookahead expression with fixed lookahead length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, zzEndRead - zzStartRead, zzMarkedPos, -2);
            { return token(yytext(), "VARIABLE ENTERA", yyline, yycolumn);
            }
            // fall through
          case 31: break;
          case 14:
            // lookahead expression with fixed lookahead length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, zzEndRead - zzStartRead, zzMarkedPos, -2);
            { return token(yytext(), "VARIABLE STR", yyline, yycolumn);
            }
            // fall through
          case 32: break;
          case 15:
            // lookahead expression with fixed lookahead length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, zzEndRead - zzStartRead, zzMarkedPos, -1);
            { return token(yytext(), "VARIABLE FLOTANTE", yyline, yycolumn);
            }
            // fall through
          case 33: break;
          case 16:
            // lookahead expression with fixed lookahead length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, zzEndRead - zzStartRead, zzMarkedPos, -2);
            { return token(yytext(), "VARIABLE FLOTANTE", yyline, yycolumn);
            }
            // fall through
          case 34: break;
          case 17:
            // lookahead expression with fixed lookahead length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, zzEndRead - zzStartRead, zzMarkedPos, -1);
            { return token(yytext(), "VARIABLE BOOLEANA", yyline, yycolumn);
            }
            // fall through
          case 35: break;
          case 18:
            // lookahead expression with fixed lookahead length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, zzEndRead - zzStartRead, zzMarkedPos, -2);
            { return token(yytext(), "VARIABLE BOOLEANA", yyline, yycolumn);
            }
            // fall through
          case 36: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
